// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('D:/lwruan/book-starter/src/components/Footer.vue')['default']
    IconCarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    IconCarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    IconCarbonLanguage: typeof import('~icons/carbon/language')['default']
    IconCarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    IconCarbonMoon: typeof import('~icons/carbon/moon')['default']
    IconCarbonSun: typeof import('~icons/carbon/sun')['default']
    LambertMaterial: typeof import('~icons/la/mbert-material')['default']
    PhysicalMaterial: typeof import('~icons/ph/ysical-material')['default']
    README: typeof import('D:/lwruan/book-starter/src/components/README.md')['default']
    Three: typeof import('D:/lwruan/book-starter/src/components/Three.vue')['default']
  }
}

export { }
